name: Create InVEST Release DOI

on:
    workflow_call:  # allow this workflow to be called from other workflows.
        inputs:
            # TODO: is there a way to share these inputs between workflow_call
            # and workflow_dispatch?
            version:
                description: The InVEST version for which we're creating a DOI
                required: true
                type: string
            datacite_instance:
                description: The target DataCite Fabrica instance, either "test" or "production".
                required: true
                type: string
            publish:
                description: If checked, DOI will be published and immutable.  Metadata is always mutable.
                required: false
                type: boolean

    workflow_dispatch:
        inputs:
            version:
                description: The InVEST version for which we're creating a DOI.
                required: true
                type: string
            datacite_instance:
                description: The target DataCite Fabrica instance.
                required: true
                default: 'test'
                type: choice
                options:
                    - test
                    - production
            publish:
                description: If checked, DOI will be published and immutable.  Metadata is always mutable.
                required: false
                type: boolean

permissions:
    contents: write

concurrency:
    cancel-in-progress: false
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    execute:
        runs-on: ubuntu-latest
        env:
            DATACITE_TEMPLATE: templates/datacite.json.template
            NEW_DATACITE_FILE: invest-releases/${{ inputs.version }}/datacite.json
            HTML_TEMPLATE: templates/release.html.template
            NEW_HTML_FILE: html/${{ inputs.version }}.html
            INDEX_HTML_TEMPLATE: templates/index.html.template
            VERSION: ${{ inputs.version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Set up python
              uses: actions/setup-python@v6
              with:
                  python-version: 3.13
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Set env variables
              run:
                  echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
                  if [[ "${{ inputs.datacite_instance }}" = "test" ]]
                  then
                    TEST=1;
                  else
                    TEST=0;
                  fi
                  echo "USE_TEST_FABRICA=$TEST" >> $GITHUB_ENV

            - name: Create new files in repo but don't overwrite
              run:
                  DATE=$(date +%Y-%M-%d)
                  if test -f ${{ env.NEW_DATACITE_FILE }}; then
                    echo "File exists; not overwriting datacite file. ${{ env.NEW_DATACITE_FILE }}"
                  else
                    python do-release.py "${{ inputs.version }}" "$DATE"
                  fi

            - name: Commit new changes
              run: |
                  git add invest-releases/**/datacite.json
                  git add html/*.html
                  git commit -m "GHA: Adding new files for version ${{ inputs.version }}"

            - name: Push changes
              run: git push origin main

            - name: Create the DOI on DataCite
              env:
                  DATACITE_USER_PASS: "${{ secrets.DATACITE_USER }}:${{ secrets.DATACITE_USER_PASS }}"
                  DATACITE_TEST_USER_PASS: "${{ secrets.DATACITE_TEST_USER }}:${{ secrets.DATACITE_TEST_USER_PASS }}"
              run: |
                  if [[ ${{ inputs.publish }} ]]
                  then
                    # Using --publish will register the DOI and also make it
                    # findable.  See https://support.datacite.org/docs/doi-states for DOI
                    # states and allowed actions.
                    PUBLISH="--publish"
                  fi
                  if [[ $USE_TEST_FABRICA = 1 ]]
                  then
                    INSTANCE="--test"
                  fi
                  python register-doi.py --auth=ENV $INSTANCE $PUBLISH $NEW_DATACITE_FILE
